# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_shelter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShelterPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='From CSV; used to prevent duplicates.', max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('species', models.CharField(db_index=True, max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('intake_date', models.DateField(blank=True, null=True)),
                ('intake_location_text', models.CharField(blank=True, max_length=300)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('IN_CARE', 'In care'), ('ADOPTED', 'Adopted'), ('REUNITED', 'Reunited'), ('UNKNOWN', 'Unknown')], db_index=True, default='IN_CARE', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shelter_pets/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='shelters.shelter')),
            ],
            options={
                'ordering': ['-intake_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['city'], name='shelters_sh_city_7a8f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['verified'], name='shelters_sh_verifie_2c8e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='shelterpet',
            index=models.Index(fields=['shelter', 'species'], name='shelters_sh_shelter_9a1b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='shelterpet',
            index=models.Index(fields=['external_id'], name='shelters_sh_extern_3d4e5f_idx'),
        ),
    ]
