# Generated by Django 4.2.28 on 2026-02-13 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shelter',
            new_name='shelters_sh_city_930b3a_idx',
            old_name='shelters_sh_city_7a8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='shelter',
            new_name='shelters_sh_verifie_5330a6_idx',
            old_name='shelters_sh_verifie_2c8e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='shelterpet',
            new_name='shelters_sh_shelter_fd3e27_idx',
            old_name='shelters_sh_shelter_9a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='shelterpet',
            new_name='shelters_sh_externa_f2b1d9_idx',
            old_name='shelters_sh_extern_3d4e5f_idx',
        ),
        migrations.AlterField(
            model_name='shelter',
            name='owner_user',
            field=models.OneToOneField(blank=True, help_text='User account that owns this shelter (shelter role).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_shelter', to=settings.AUTH_USER_MODEL),
        ),
    ]
