# Generated by Django 4.2.28 on 2026-02-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='accounts_us_role_e16858_idx',
            old_name='accounts_us_role_8b7b0d_idx',
        ),
    ]
