# Generated by Django 4.2.28 on 2026-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='petreport',
            new_name='reports_pet_report__3c3114_idx',
            old_name='reports_pet_report__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='petreport',
            new_name='reports_pet_species_478f45_idx',
            old_name='reports_pet_species_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='petreport',
            new_name='reports_pet_created_d7d6e1_idx',
            old_name='reports_pet_created_7g8h9i_idx',
        ),
        migrations.AlterField(
            model_name='petreport',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='petreport',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50),
        ),
    ]
